################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 0
[en.params]
footer_content = "Everything you need to get started in SEO"
# copyright
copyright = "Copyright 2024"
